name: Graphs CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [graphs]

permissions:
  contents: write

jobs:
  graphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/graphs@v1.2.22
        with:
          token: ${{ secrets.GH_PAT }}
