name: Static Site CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [site]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.43.1
        with:
          command: "site"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: __sapper__/export
      - id: deployment
        uses: actions/deploy-pages@v4
